CREATE TABLE IF NOT EXISTS Avatar (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name   VARCHAR(30),
    Link    VARCHAR(130)
);

CREATE TABLE IF NOT EXISTS User (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Login   VARCHAR(30),
    Password    VARCHAR(200),
    AvatarId INT,
    FOREIGN KEY (AvatarId)  REFERENCES Avatar (Id)
);

CREATE TABLE IF NOT EXISTS Category (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name   VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Item (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name    VARCHAR(30),
    Link    VARCHAR(130),
    Price   INT
);

CREATE TABLE IF NOT EXISTS ItemCat (
    ItemId    INT,
    FOREIGN KEY (ItemId)  REFERENCES Item (Id),
    CatId   INT,
    FOREIGN KEY (CatId)  REFERENCES Category (Id)
);

CREATE TABLE IF NOT EXISTS BasketItem (
    UserId    INT,
    FOREIGN KEY (UserId)  REFERENCES User (Id),
    ItemId        INT,
    FOREIGN KEY (ItemId)  REFERENCES Item (Id),
    Buy TINYINT DEFAULT (0)
);

CREATE TABLE IF NOT EXISTS Order (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name    VARCHAR(30),
    Link    VARCHAR(130),
    Price   INT
);

CREATE TABLE IF NOT EXISTS ItemCat (
    ItemId    INT,
    FOREIGN KEY (ItemId)  REFERENCES Item (Id),
    CatId   INT,
    FOREIGN KEY (CatId)  REFERENCES Category (Id)
);
